### ISSUE TITLE
Runtime Issue with Heroku Stack 20

### ISSUE THREAD

**Issue by Smallz2** [uwi-info3180/info3180-lab1#1]
Heroku build fail with the current runtime specified in runtime.txt. 

Build error: 
remote: -----> Building on the Heroku-20 stack
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/python.tgz
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed

Currently specified
`python-3.7.1` 

Building with my runtime 
`python-3.8.5`
probably would also work with 3.8.0

Heroku docs for more information for python runtime in stack-20
https://devcenter.heroku.com/articles/heroku-20-stack

**Comment by ylynfatt** [comment]
@Smallz2 `runtime.txt` has been updated to `python-3.9.1`.
